Use Dart 2.11 beta for CI and dry run publish

diff --git a/.github/workflows/cqrs-test.yml b/.github/workflows/cqrs-test.yml
--- a/.github/workflows/cqrs-test.yml
+++ b/.github/workflows/cqrs-test.yml
@@ -19,7 +19,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        dart_release: ['2.10', '2.11-dev']
+        dart_release: ['2.10', '2.11-beta']
       
     container:
       image: google/dart:${{ matrix.dart_release }}
@@ -50,3 +50,7 @@ jobs:
 
       - name: Run tests
         run: dart test
+
+      - name: Dry run pub publish
+        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
+        run: dart pub publish --dry-run || true
