Add pub publish dry run to CI

diff --git a/.github/workflows/login_client-test.yml b/.github/workflows/login_client-test.yml
--- a/.github/workflows/login_client-test.yml
+++ b/.github/workflows/login_client-test.yml
@@ -57,3 +57,7 @@ jobs:
 
       - name: Run tests
         run: flutter test
+
+      - name: Dry run pub publish
+        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
+        run: pub publish --dry-run || true
